/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

res_calculo *
suma_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static res_calculo  result;

	xdr_free(xdr_res_calculo, &result);
	result.res_calculo_u.resultado = arg1 + arg2;

	return &result;
}

res_calculo *
resta_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static res_calculo  result;

	xdr_free(xdr_res_calculo, &result);
	result.res_calculo_u.resultado = arg1 - arg2;

	return &result;
}

res_calculo *
multiplicacion_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static res_calculo  result;

	xdr_free(xdr_res_calculo, &result);
	result.res_calculo_u.resultado = arg1 * arg2;

	return &result;
}

res_calculo *
division_1_svc(int arg1, int arg2,  struct svc_req *rqstp)
{
	static res_calculo  result;

	xdr_free(xdr_res_calculo, &result);
	result.res_calculo_u.resultado = arg1 / arg2;

	return &result;
}
