/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

void basicas (char *host, int operando1, char operacion, int operando2) {
	CLIENT *clnt;
	res_calculo * result;

	#ifndef	DEBUG
		clnt = clnt_create (host, CALCULADORAPROG, CALCULADORAVER, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

	if(operacion == '+')
		result = suma_1(operando1, operando2, clnt);
	else if(operacion == '-')
		result = resta_1(operando1, operando2, clnt);
	else if(operacion == 'x')
		result = multiplicacion_1(operando1, operando2, clnt);
	else if(operacion == '/')
		result = division_1(operando1, operando2, clnt);
	else
		perror("Operación inválida\n");

	if(result == (res_calculo *) NULL)
		clnt_perror(clnt, "call failed");

	printf("El resultado es: %d\n", result->res_calculo_u.resultado);

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}

void calculadoraprog_1(char *host) {
	CLIENT *clnt;
	res_calculo  *result_1;
	int suma_1_arg1;
	int suma_1_arg2;
	res_calculo  *result_2;
	int resta_1_arg1;
	int resta_1_arg2;
	res_calculo  *result_3;
	int multiplicacion_1_arg1;
	int multiplicacion_1_arg2;
	res_calculo  *result_4;
	int division_1_arg1;
	int division_1_arg2;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORAPROG, CALCULADORAVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_1(suma_1_arg1, suma_1_arg2, clnt);
	if (result_1 == (res_calculo *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = resta_1(resta_1_arg1, resta_1_arg2, clnt);
	if (result_2 == (res_calculo *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = multiplicacion_1(multiplicacion_1_arg1, multiplicacion_1_arg2, clnt);
	if (result_3 == (res_calculo *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = division_1(division_1_arg1, division_1_arg2, clnt);
	if (result_4 == (res_calculo *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	int operando1 = atoi(argv[2]);
	int operando2 = atoi(argv[4]);

	char operacion = *argv[3];

	basicas(host, operando1, operacion, operando2);
exit (0);
}
